package com.example.taskhabit.ui.theme

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Bottom nav
    val navToday: String,
    val navHabits: String,
    val navStats: String,
    val navBadges: String,
    // Top bar
    val greeting: String,
    // Today screen
    val todaysRituals: String,
    val keepStreakAlive: String,
    val currentMomentum: String,
    val addFirstHabit: String,
    val keepGoingGreat: String,
    val completedLabel: String,
    // Habits screen
    val myHabits: String,
    val completedTodayOf: String,
    val filterAll: String,
    val filterPending: String,
    val filterCompleted: String,
    val noPendingHabits: String,
    val noCompletedHabits: String,
    val noHabitsYet: String,
    // Add habit
    val addNewHabit: String,
    val newRitual: String,
    val startYourFlow: String,
    val whatIsHabit: String,
    val habitPlaceholder: String,
    val frequency: String,
    val daily: String,
    val custom: String,
    val reminderTime: String,
    val category: String,
    val accentColor: String,
    val smartSuggestions: String,
    val smartSuggestionText: String,
    val createHabit: String,
    val selectDays: String,
    val confirm: String,
    val cancel: String,
    val monday: String,
    val tuesday: String,
    val wednesday: String,
    val thursday: String,
    val friday: String,
    val saturday: String,
    val sunday: String,
    // Edit habit
    val editHabit: String,
    val habitName: String,
    val saveChanges: String,
    val back: String,
    // Profile
    val profile: String,
    val userName: String,
    val email: String,
    val birthDate: String,
    val birthDateHint: String,
    val saveProfile: String,
    val profileBannerLabel: String,
    val profileBannerSub: String,
    // Settings
    val settings: String,
    val language: String,
    val languageSubtitle: String,
    // Stats
    val totalHabitsCompleted: String,
    val bestStreak: String,
    val days: String,
    val weeklyRituals: String,
    val weeklySubtitle: String,
    val kineticFlow: String,
    val areasOfGrowth: String,
)

val EnglishStrings = AppStrings(
    navToday = "Today", navHabits = "Habits", navStats = "Stats", navBadges = "Badges",
    greeting = "Kinetic Flow",
    todaysRituals = "Today's Rituals", keepStreakAlive = "Keep the streak alive",
    currentMomentum = "Current Momentum",
    addFirstHabit = "Add your first habit to get started.",
    keepGoingGreat = "Keep going, you're doing great!",
    completedLabel = "Completed",
    myHabits = "My Habits", completedTodayOf = "completed today",
    filterAll = "All", filterPending = "Pending", filterCompleted = "Completed",
    noPendingHabits = "No pending habits.\nGreat job today!",
    noCompletedHabits = "No completed habits yet.\nKeep going!",
    noHabitsYet = "No habits yet.\nCreate your first ritual!",
    addNewHabit = "Add New Habit", newRitual = "NEW RITUAL", startYourFlow = "Start Your Flow",
    whatIsHabit = "What is the habit?", habitPlaceholder = "e.g. Morning Meditation",
    frequency = "Frequency", daily = "Daily", custom = "Custom",
    reminderTime = "Reminder Time", category = "Category", accentColor = "Accent Color",
    smartSuggestions = "Smart Suggestions",
    smartSuggestionText = "We've noticed you're usually active at 8:00 AM. Want to pair this with your 'Coffee' ritual?",
    createHabit = "Create Habit",
    selectDays = "Select Days", confirm = "Confirm", cancel = "Cancel",
    monday = "Mon", tuesday = "Tue", wednesday = "Wed", thursday = "Thu",
    friday = "Fri", saturday = "Sat", sunday = "Sun",
    editHabit = "Edit Habit", habitName = "Habit Name", saveChanges = "Save Changes", back = "Back",
    profile = "Profile", userName = "Name", email = "Email",
    birthDate = "Birth Date", birthDateHint = "DD/MM/YYYY",
    saveProfile = "Save Profile", profileBannerLabel = "MY PROFILE", profileBannerSub = "Your Identity",
    settings = "Settings", language = "Language", languageSubtitle = "Choose your preferred language",
    totalHabitsCompleted = "TOTAL HABITS COMPLETED", bestStreak = "BEST STREAK", days = "Days",
    weeklyRituals = "Weekly Rituals", weeklySubtitle = "Performance over the last 7 days",
    kineticFlow = "Kinetic Flow", areasOfGrowth = "Areas of Growth",
)

val PortugueseStrings = AppStrings(
    navToday = "Hoje", navHabits = "Hábitos", navStats = "Stats", navBadges = "Conquistas",
    greeting = "Fluxo Cinético",
    todaysRituals = "Rituais de Hoje", keepStreakAlive = "Mantenha a sequência",
    currentMomentum = "Progresso Atual",
    addFirstHabit = "Adicione seu primeiro hábito para começar.",
    keepGoingGreat = "Continue, você está indo muito bem!",
    completedLabel = "Concluído",
    myHabits = "Meus Hábitos", completedTodayOf = "concluídos hoje",
    filterAll = "Todos", filterPending = "Pendentes", filterCompleted = "Concluídos",
    noPendingHabits = "Nenhum hábito pendente.\nÓtimo trabalho hoje!",
    noCompletedHabits = "Nenhum hábito concluído ainda.\nContinue!",
    noHabitsYet = "Nenhum hábito ainda.\nCrie seu primeiro ritual!",
    addNewHabit = "Novo Hábito", newRitual = "NOVO RITUAL", startYourFlow = "Comece Seu Fluxo",
    whatIsHabit = "Qual é o hábito?", habitPlaceholder = "ex: Meditação Matinal",
    frequency = "Frequência", daily = "Diário", custom = "Personalizado",
    reminderTime = "Horário", category = "Categoria", accentColor = "Cor de Destaque",
    smartSuggestions = "Sugestões Inteligentes",
    smartSuggestionText = "Notamos que você costuma estar ativo às 8:00. Quer combinar com seu ritual 'Café'?",
    createHabit = "Criar Hábito",
    selectDays = "Selecionar Dias", confirm = "Confirmar", cancel = "Cancelar",
    monday = "Seg", tuesday = "Ter", wednesday = "Qua", thursday = "Qui",
    friday = "Sex", saturday = "Sáb", sunday = "Dom",
    editHabit = "Editar Hábito", habitName = "Nome do Hábito", saveChanges = "Salvar Alterações", back = "Voltar",
    profile = "Perfil", userName = "Nome", email = "E-mail",
    birthDate = "Data de Nascimento", birthDateHint = "DD/MM/AAAA",
    saveProfile = "Salvar Perfil", profileBannerLabel = "MEU PERFIL", profileBannerSub = "Sua Identidade",
    settings = "Configurações", language = "Idioma", languageSubtitle = "Escolha o idioma preferido",
    totalHabitsCompleted = "TOTAL DE HÁBITOS CONCLUÍDOS", bestStreak = "MELHOR SEQUÊNCIA", days = "Dias",
    weeklyRituals = "Rituais Semanais", weeklySubtitle = "Desempenho nos últimos 7 dias",
    kineticFlow = "Fluxo Cinético", areasOfGrowth = "Áreas de Crescimento",
)

val LocalStrings = compositionLocalOf<AppStrings> { EnglishStrings }
